# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
#-------------CentOS_VM---------------
  config.vm.define "CentOS" do |cent|
    cent.vm.box = "centos/7"
    cent.vm.network "forwarded_port", guest: 8090, host: 8080
    cent.vm.network "forwarded_port", guest: 3306, host: 3306
    cent.vm.hostname = "centos"
    cent.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    cent.vm.provision "shell", path: "bootstrap.sh"
  end

end

